### ISSUE TITLE
installation error in makefile

### ISSUE THREAD

**Issue by maheshs93** [SCIInstitute/Tuvok#2]
when trying to install Imagevis3d getting a error in makefile

error: syntax error in E:\ImgVis\build-ImageVis3D-Desktop_Qt_5_7_0_MSVC2013_64bit-Debug\ImageVis3D\Makefile line 1

<?xml version="1.0" encoding="UTF-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<ItemGroup Label="ProjectConfigurations">
<ProjectConfiguration Include="Debug|x64">
<Configuration>Debug</Configuration>
<Platform>x64</Platform>
</ProjectConfiguration>
<ProjectConfiguration Include="Release|x64">
<Configuration>Release</Configuration>
<Platform>x64</Platform>
</ProjectConfiguration>
............................

**Comment by tfogal** [comment]
There are no makefiles in the MSVC build, just solution files; please use those.
Also, this is the Tuvok forum; ImageVis3D uses Tuvok, but they're not the same.  Please reopen the request in that forum if I'm missing something here.
