### ISSUE TITLE
Error in Tuvok/Basics/SysTools.cpp

### ISSUE THREAD

**Issue by maheshs93** [SCIInstitute/Tuvok#3]
Please can you helps me the changes in the code
	bool GetTempDirectory(std::string& path) {
#ifdef DETECTED_OS_WINDOWS
		
		DWORD result = ::GetTempPathA(0, "");
		if (result == 0) return false;
		std::vector<char> tempPath(result + 1);
		result = ::GetTempPathA(static_cast<DWORD>(tempPath.size()), &tempPath[0]);
		if ((result == 0) || (result >= tempPath.size())) return false;
		path = std::string(tempPath.begin(), tempPath.begin() + static_cast<std::size_t>(result));
		return true;
#else
		char * pointer;
		pointer = tmpnam(NULL);
		path = GetPath(std::string(pointer));
		return true;
#endif
	}

	bool GetTempDirectory(std::wstring& path) {
#ifdef DETECTED_OS_WINDOWS
		DWORD result = ::GetTempPathW(0, L"");
		if (result == 0) return false;
		std::vector<WCHAR> tempPath(result + 1);
		result = ::GetTempPathW(static_cast<DWORD>(tempPath.size()), &tempPath[0]);
		if ((result == 0) || (result >= tempPath.size())) return false;
		path = std::wstring(tempPath.begin(), tempPath.begin() + static_cast<std::size_t>(result));
		return true;
#else
		// too lazy to find the unicode version for linux and mac
		std::string astrPath;
		if (!GetTempDirectory(astrPath)) return false;
		path = std::wstring(astrPath.begin(), astrPath.end());
		return true;
#endif
	}

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'DWORD GetTempPathW(DWORD,LPWSTR)': cannot convert argument 2 from 'const wchar_t [1]' to 'LPWSTR'	Tuvok	E:\Mahesh\New folder\ImageVis3D-7ed1d545821a3458a8617fc4c6a541dafd690caa\Tuvok\Basics\SysTools.cpp	1097

**Comment by tfogal** [comment]
could you fix the formatting and point out line 1097?  I can't see what we're looking at here.

**Comment by maheshs93** [comment]
#else
char * pointer;
pointer = tmpnam(NULL);
path = GetPath(std::string(pointer));
return true;
#endif
}

1097    bool GetTempDirectory(std::wstring& path) {
1098    #ifdef DETECTED_OS_WINDOWS
1099    DWORD result = ::GetTempPathW(0, L"");
1100    if (result == 0) return false;
1101    std::vector tempPath(result + 1);
            result = ::GetTempPathW(static_cast(tempPath.size()), &tempPath[0]);
            if ((result == 0) || (result >= tempPath.size())) return false;
path = std::wstring(tempPath.begin(), tempPath.begin() + static_caststd::size_t(result));
return true;
#else
// too lazy to find the unicode version for linux and mac
std::string astrPath;
if (!GetTempDirectory(astrPath)) return false;
path = std::wstring(astrPath.begin(), astrPath.end());
return true;
#endif
}

**Comment by tfogal** [comment]
It looks like line 1097 is the first line of the definition.  That suggests the warning is actually about an issue converting whatever is _calling_ the function to a std::wstring&.  Is there more to the error message?

Also it sounds like that code is not very unicode friendly (from the comment); patches welcome, of course.

**Comment by maheshs93** [comment]
Actually in error the line number is changed

**Comment by tfogal** [comment]
ESR can be a bit more of a jerk than he should be, but he's basically dead on with this:

  http://catb.org/~esr/faqs/smart-questions.html

It looks like you're modifying the code in ways that are breaking things, and then reporting what you've broken here and asking us to debug it.  Please don't do that.  Please grok the above, and if there is an actual problem with Tuvok, open a new issue.

**Comment by maheshs93** [comment]
Thanks for your reply
